<template>
  <!-- Footer -->
  <footer class="page-footer font-small blue pt-4">

    <!-- Footer Links -->
    <div class="container-fluid text-center text-md-left">
    </div>
    <!-- Footer Links -->
    <!-- Copyright -->
    <div class="footer-copyright text-center py-3">© 2019 Bitcamp Jongno  
      | SeungHwan Jeon
    </div>
    <!-- Copyright -->
  </footer>
  <!-- Footer --> 
</template>
<script>
export default {
    
}
</script>
<style scoped>

</style>
