<template>
   <!-- Footer -->
<footer class="page-footer font-small blue pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase"></h5>
        <p></p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase"></h5>

        <ul class="list-unstyled">
          <li>
            <a href="#!"></a>
          </li>
          
        </ul>

      </div>
      <!-- Grid column -->

      

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 전승환 :
    <!-- <a href="https://mdbootstrap.com/education/bootstrap/"> </a> -->woon.com
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer --> 
</template>
<script>
export default {
    
}
</script>
<style scoped>

</style>
