<template>
   <!-- Footer -->
<footer class="page-footer font-small blue pt-4">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    
    

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2019 전승환 :
    <!-- <a href="https://mdbootstrap.com/education/bootstrap/"> </a> -->woon.com
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer --> 
</template>
<script>
export default {
    
}
</script>
<style scoped>

</style>
